# Generated by Django 6.0.5 on 2026-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_permissions_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroupmodel',
            options={
                'default_permissions': (),
                'permissions': [
                    ('view_permissiongroup', 'Can view and list permission groups'),
                    ('add_permissiongroup', 'Can create new permission groups'),
                    ('change_permissiongroup', "Can modify a permission group's name and permissions"),
                    ('delete_permissiongroup', 'Can delete permission groups')
                ],
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups'
            },
        ),
        migrations.AlterModelOptions(
            name='rolemodel',
            options={
                'default_permissions': (),
                'permissions': [
                    ('view_role', 'Can view and list roles'), 
                    ('add_role', 'Can create new roles'), 
                    ('change_role', "Can modify a role's name, description and assigned permissions"), 
                    ('delete_role', 'Can permanently delete roles'), 
                    ('activate_role', 'Can activate or deactivate roles')
                ],
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles'
            },
        ),
        migrations.AlterModelOptions(
            name='userrolemodel',
            options={
                'default_permissions': (),
                'permissions': [
                    ('view_userrole', 'Can view role assignments'), 
                    ('assign_role', 'Can assign roles to users'), 
                    ('revoke_role', 'Can revoke role assignments from users')
                ], 
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments'
            },
        ),
    ]
